import { requireAuth, initAppShell, fetchAll, $, money, emptyState, makeChart, toast } from '../../js/shared.js';
import { db, collection, addDoc, serverTimestamp } from '../../js/firebase-config.js';
const { profile } = await requireAuth(['Admin']); initAppShell('admin','forecasting',profile);
let products=[], sales=[], latest=null;
function daysBetween(a,b){return Math.max(1, Math.ceil((b-a)/86400000));}
async function load(){products=await fetchAll('products'); sales=await fetchAll('sales'); $('#forecastProduct').innerHTML='<option value="">Select product</option>'+products.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''); renderEmpty();}
function renderEmpty(){ $('#forecastStats').innerHTML=['Current Stock','Average Daily Sale','Stock Finish','Reorder Qty'].map(x=>`<div class="glass stat-card"><div class="stat-label">${x}</div><div class="stat-value">0</div><div class="stat-hint">Select product</div></div>`).join(''); $('#forecastOutput').innerHTML=emptyState('No forecast yet','Select a product and run forecast.'); makeChart($('#forecastChart'),'line',{labels:[],datasets:[{label:'Demand',data:[]}]});}
function run(){const p=products.find(x=>x.id===$('#forecastProduct').value); if(!p) return toast('Select product.','err'); const ps=sales.filter(s=>s.productId===p.id); const total=ps.reduce((a,s)=>a+Number(s.quantity||0),0); const dates=ps.map(s=>s.createdAt?.toDate?.()).filter(Boolean).sort((a,b)=>a-b); const days=dates.length?daysBetween(dates[0], new Date()):1; const avg=total/days; const finish=avg>0?Math.ceil(Number(p.stock||0)/avg):Infinity; const reorder=Math.ceil(avg*30); const expected=Number.isFinite(finish)?new Date(Date.now()+finish*86400000):null; latest={productId:p.id,productName:p.name,currentStock:Number(p.stock||0),averageDailySale:avg,stockFinishDays:Number.isFinite(finish)?finish:null,expectedOutOfStockDate:expected?expected.toISOString().slice(0,10):'No sales trend yet',suggestedReorderQuantity:reorder,createdAt:new Date().toISOString()}; $('#forecastStats').innerHTML=[['Current Stock',p.stock||0,'Available now'],['Average Daily Sale',avg.toFixed(2),'Total sold / days'],['Stock Finish',Number.isFinite(finish)?`${finish} days`:'No trend','Estimated'],['Reorder Qty',reorder,'Avg × 30 days']].map(x=>`<div class="glass stat-card"><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-hint">${x[2]}</div></div>`).join(''); $('#forecastOutput').innerHTML=`<div class="space-y-3 leading-8"><p><b>Product:</b> ${p.name}</p><p><b>Current Stock:</b> ${p.stock}</p><p><b>Average Daily Sale:</b> ${avg.toFixed(2)}</p><p><b>Estimated Stock Finish Date:</b> ${expected?expected.toLocaleDateString('en-IN'):'No sales trend yet'}</p><p><b>Suggested Reorder Quantity:</b> ${reorder} units</p></div>`; const labels=[...Array(30)].map((_,i)=>`Day ${i+1}`); const demand=labels.map((_,i)=>Math.max(0, Number(p.stock||0)-avg*(i+1))); makeChart($('#forecastChart'),'line',{labels,datasets:[{label:'Projected Stock',data:demand,tension:.35,fill:true},{label:'Demand',data:labels.map((_,i)=>avg*(i+1)),tension:.35}]});}
$('#runForecast').onclick=run; $('#saveForecast').onclick=async()=>{if(!latest) return toast('Run forecast first.','err'); await addDoc(collection(db,'forecasting'),{...latest,createdAt:serverTimestamp(),savedBy:profile.id}); toast('Forecast saved.');}; load();
