import { requireAuth, initAppShell, fetchAll, $, $$, toast, statusFor, badgeForStatus, money, emptyState, createNotification } from '../../js/shared.js';
import { db, doc, updateDoc, serverTimestamp, collection, query, where, orderBy } from '../../js/firebase-config.js';
const { profile } = await requireAuth(['Admin','Manager']); initAppShell('admin','inventory',profile);
let products=[], sales=[], batches=[];
const modal=$('#stockModal');
function renderStats(){ const low=products.filter(p=>statusFor(p.stock,p.minStock)==='Low Stock'), out=products.filter(p=>statusFor(p.stock,p.minStock)==='Out of Stock'); $('#inventoryStats').innerHTML=[['Current Products',products.length,'Total SKUs'],['Low Stock',low.length,'Needs reorder'],['Out of Stock',out.length,'Unavailable'],['Stock Value',money(products.reduce((a,p)=>a+Number(p.stock||0)*Number(p.costPrice||0),0)),'At cost price']].map(x=>`<div class="glass stat-card"><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-hint">${x[2]}</div></div>`).join(''); }
function getBatchStatus(batch){const today=new Date().toISOString().slice(0,10);if(batch.status==='Disposed'||batch.status==='Empty')return batch.status;if(!batch.expiryDate)return'Active';if(batch.expiryDate<today)return'Expired';const daysLeft=Math.ceil((new Date(batch.expiryDate).getTime()-new Date(today).getTime())/86400000);return daysLeft<=30?'Near Expiry':'Active';}
function formatDate(value){if(!value)return'-';const date=new Date(`${value}T00:00:00`);if(Number.isNaN(date.getTime()))return value;return date.toLocaleDateString('en-IN');}
function renderTable(){ const q=$('#inventorySearch').value.toLowerCase(), cat=$('#inventoryCategory').value, st=$('#inventoryStatus').value; const rows=products.filter(p=>(p.name||'').toLowerCase().includes(q)&&(!cat||p.category===cat)&&(!st||statusFor(p.stock,p.minStock)===st)); $('#inventoryTable').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Current Stock</th><th>Minimum</th><th>Status</th><th>Batches</th><th>Action</th></tr></thead><tbody>${rows.map(p=>{const productBatches=batches.filter(b=>b.productId===p.id);const batchHtml=productBatches.length?`<button class="btn btn-ghost btn-sm" onclick="showBatches('${p.id}')">${productBatches.length} batch${productBatches.length>1?'es':''}</button>`:'<span class="text-slate-400">No batches</span>';return`<tr class="${statusFor(p.stock,p.minStock)!=='Available'?'warning-row':''}"><td class="font-black">${p.name}</td><td>${p.category||'-'}</td><td>${p.stock||0}</td><td>${p.minStock||0}</td><td>${badgeForStatus(statusFor(p.stock,p.minStock))}</td><td>${batchHtml}</td><td><button class="btn btn-ghost btn-sm" onclick="openStock('${p.id}')">Update</button></td></tr>`}).join('')}</tbody></table></div>`:emptyState('No stock records','Add products first.'); }
function renderMovement(){ const map=new Map(); sales.forEach(s=>map.set(s.productName,(map.get(s.productName)||0)+Number(s.quantity||0))); const sorted=[...map].sort((a,b)=>b[1]-a[1]); $('#movementList').innerHTML = sorted.length ? `<div class="space-y-3"><div><b>Fast-moving</b>${sorted.slice(0,5).map(x=>`<div class="flex justify-between border-b border-slate-700/50 py-2"><span>${x[0]}</span><span class="badge badge-ok">${x[1]}</span></div>`).join('')}</div><div class="pt-4"><b>Slow-moving</b>${sorted.slice(-5).reverse().map(x=>`<div class="flex justify-between border-b border-slate-700/50 py-2"><span>${x[0]}</span><span class="badge badge-warn">${x[1]}</span></div>`).join('')}</div></div>` : emptyState('No movement data','Sales will appear here.'); }
window.openStock=id=>{const p=products.find(x=>x.id===id); $('#stockProductId').value=id; $('#stockProductName').value=p.name; $('#stockNewQty').value=p.stock||0; modal.classList.add('show')}; $$('[data-close-modal]').forEach(b=>b.onclick=()=>modal.classList.remove('show'));
$('#stockForm').onsubmit=async e=>{e.preventDefault();const id=$('#stockProductId').value, qty=Number($('#stockNewQty').value);const p=products.find(x=>x.id===id); await updateDoc(doc(db,'products',id),{stock:qty,status:statusFor(qty,p.minStock),updatedAt:serverTimestamp()}); toast('Stock updated.'); modal.classList.remove('show'); load();};
$('#generateStockAlerts').onclick=async()=>{let count=0; for(const p of products){const st=statusFor(p.stock,p.minStock); if(st!=='Available'){count++; await createNotification(`${p.name} stock is ${st}. Current stock: ${p.stock}. Minimum: ${p.minStock}.`,'stock');}} toast(count?`${count} alerts generated.`:'No low stock alerts.');};
window.showBatches=async(productId)=>{const p=products.find(x=>x.id===productId);const productBatches=batches.filter(b=>b.productId===productId).sort((a,b)=>(a.expiryDate||'').localeCompare(b.expiryDate||''));const html=productBatches.map(b=>{const status=getBatchStatus(b);return `<div class="glass p-3 rounded-xl border-l-4 ${status==='Expired'?'border-red-500':status==='Near Expiry'?'border-amber-500':status==='Disposed'?'border-red-500':status==='Empty'?'border-slate-500':'border-emerald-500'}"><div class="flex justify-between items-center"><div><span class="font-bold">${b.batchNumber}</span> <span class="text-sm text-slate-400 ml-2">${formatDate(b.manufactureDate)} → ${formatDate(b.expiryDate)}</span></div><div class="flex items-center gap-3"><span class="${status==='Expired'?'text-red-400':status==='Near Expiry'?'text-amber-400':status==='Disposed'?'text-red-400':status==='Empty'?'text-slate-400':'text-emerald-400'} font-medium">${status}</span><span class="font-bold ${b.remainingQuantity<=0?'text-red-400':''}">${b.remainingQuantity||0} / ${b.purchasedQuantity||0}</span></div></div></div>`}).join('')||'<p class="text-slate-400">No batches for this product.</p>';const modal=document.createElement('div');modal.className='modal-backdrop show';modal.innerHTML=`<div class="modal-card glass-strong p-6"><div class="flex justify-between items-center mb-4"><h3 class="text-xl font-black">Batches for ${p.name}</h3><button class="btn btn-ghost btn-sm" onclick="this.closest('.modal-backdrop').remove()">✕</button></div><div class="space-y-2 max-h-96 overflow-y-auto">${html}</div></div>`;document.body.appendChild(modal);};
async function load(){ products=await fetchAll('products'); sales=await fetchAll('sales'); batches=await fetchAll('productBatches'); $('#inventoryCategory').innerHTML='<option value="">All categories</option>'+[...new Set(products.map(p=>p.category).filter(Boolean))].map(c=>`<option>${c}</option>`).join(''); renderStats(); renderTable(); renderMovement(); }
['inventorySearch','inventoryCategory','inventoryStatus'].forEach(id=>$('#'+id).addEventListener('input',renderTable)); $('#refreshInventory').onclick=load; load();