import { requireAuth, initAppShell, fetchAll, $, toast, setBusy, money, dateText, emptyState, statusFor, createNotification } from '../../js/shared.js';
import { db, collection, addDoc, doc, updateDoc, serverTimestamp, runTransaction } from '../../js/firebase-config.js';
const { profile } = await requireAuth(['Admin','Manager']); initAppShell('admin','purchases',profile); let products=[], purchases=[], batches=[];
async function load(){products=await fetchAll('products');purchases=await fetchAll('purchases');batches=await fetchAll('productBatches');$('#purchaseProduct').innerHTML='<option value="">Choose product</option>'+products.map(p=>`<option value="${p.id}">${p.name} — current ${getTotalStock(p.id)}</option>`).join('');render();}
function getTotalStock(productId){return batches.filter(b=>b.productId===productId).reduce((sum,b)=>sum+Number(b.remainingQuantity||0),0);}
function render(){ $('#purchasesTable').innerHTML=purchases.length?`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Supplier</th><th>Price</th><th>Batch</th><th>MFG</th><th>EXP</th><th>Purchase Date</th><th>Saved</th></tr></thead><tbody>${purchases.map(p=>`<tr><td class="font-black">${p.productName}</td><td>${p.quantity}</td><td>${p.supplierName||'-'}</td><td>${money(p.purchasePrice)}</td><td>${p.batchNumber||'-'}</td><td>${p.manufactureDate||'-'}</td><td>${p.expiryDate||'-'}</td><td>${p.purchaseDate||'-'}</td><td>${dateText(p.createdAt)}</td></tr>`).join('')}</tbody></table></div>`:emptyState('No restock history','Add stock to save purchase records.'); }
$('#purchaseDate').value=new Date().toISOString().slice(0,10); $('#purchaseMfgDate').value=new Date().toISOString().slice(0,10);
$('#purchaseForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);try{const p=products.find(x=>x.id===$('#purchaseProduct').value); if(!p) throw new Error('Select product.'); const qty=Number($('#purchaseQty').value); const mfgDate=$('#purchaseMfgDate').value; const expDate=$('#purchaseExpDate').value; if(!mfgDate) throw new Error('Manufacture date is required.'); if(!expDate) throw new Error('Expiry date is required.'); if(expDate<=mfgDate) throw new Error('Expiry must be after manufacture.'); const supplier=$('#purchaseSupplier').value.trim(); const price=Number($('#purchasePrice').value||0); let newTotalStock=0; const batchNumber=`${p.name.slice(0,3).toUpperCase()}-${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}-${Date.now().toString().slice(-4)}`; await runTransaction(db,async tx=>{const ref=doc(db,'products',p.id);const snap=await tx.get(ref);const cur=Number(snap.data().stock||0);newTotalStock=cur+qty;tx.update(ref,{stock:newTotalStock,status:statusFor(newTotalStock,snap.data().minStock),updatedAt:serverTimestamp()});const batchRef=doc(collection(db,'productBatches'));tx.set(batchRef,{productId:p.id,productName:p.name,batchNumber,manufactureDate:mfgDate,expiryDate:expDate,purchasedQuantity:qty,remainingQuantity:qty,supplierName:supplier,purchasePrice:price,status:getBatchStatus({expiryDate}),createdAt:serverTimestamp(),createdBy:profile.id,soldQuantity:0,disposalRecords:[]});}); await addDoc(collection(db,'purchases'),{productId:p.id,productName:p.name,quantity:qty,supplierName:supplier,purchasePrice:price,purchaseDate:$('#purchaseDate').value,batchNumber,manufactureDate:mfgDate,expiryDate:expDate,createdAt:serverTimestamp(),createdBy:profile.id}); await createNotification(`Restock added: ${p.name} +${qty} (Batch: ${batchNumber}). New stock: ${newTotalStock}.`,'purchase'); toast('Stock increased successfully.'); e.target.reset(); $('#purchaseDate').value=new Date().toISOString().slice(0,10); $('#purchaseMfgDate').value=new Date().toISOString().slice(0,10); load();}catch(err){toast(err.message,'err')}finally{setBusy(btn,false)}};
function getBatchStatus(batch){const today=new Date().toISOString().slice(0,10);if(!batch.expiryDate)return'Active';if(batch.expiryDate<today)return'Expired';const daysLeft=Math.ceil((new Date(batch.expiryDate).getTime()-new Date(today).getTime())/86400000);return daysLeft<=30?'Near Expiry':'Active';}
load();